'use client';

import { createContext, useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const ThemeContext = createContext(null)

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [theme, setTheme] = useState('dark')
  const toggleTheme = () => {
    setTheme((currentTheme) => (currentTheme === 'light' ? 'dark' : 'light'))
  }
  return (
    <html lang="en">
        <ThemeContext.Provider value={{theme, toggleTheme}}>
      <body className={inter.className} id={theme}>
        {children}
        </body>
        </ThemeContext.Provider>
    </html>
  )
}
