import Head from "next/head";
import FetchData from "../components/fetchdata";
import SWRfetch from "../components/swrfetch";
import Axios from "../components/axios";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Posts from Api</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <h1>Results:</h1>
      {/* <FetchData /> */}
      {/* <SWRfetch /> */}
      <Axios />
    </div>
  );
}